sudo: required
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
os:
  - linux
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libopenmpi-dev
  - cpanm --verbose --no-interactive --notest https://github.com/jvolkening/Parallel-MPI-Simple/archive/0.101.tar.gz
#addons:
  #apt:
    #sources:
    #- ubuntu-toolchain-r-test
    #packages:
    #- libopenmpi-dev
